#!/usr/bin/env python3
"""probe_inventory_audit.py — auto-generate INVENTORY.md for the probe library.

Walks `src/personascope/probes/` and emits a markdown table per category listing:
  - module file
  - whether it's `external/` (cited) or top-level (ours)
  - exported `make_*` factories
  - import health (does it import cleanly?)

Run:
    python scripts/probe_inventory_audit.py
    python scripts/probe_inventory_audit.py --out INVENTORY.md

Output is deterministic — safe to commit. Re-run after adding/moving probes.
"""

from __future__ import annotations

import argparse
import importlib
import pkgutil
import sys
from pathlib import Path
from typing import Optional


def _walk_probe_modules():
    """Yield (qualname, module-or-None, error-or-None) for every probe submodule."""
    import personascope.probes as probes_pkg
    probes_root = Path(probes_pkg.__file__).parent
    for info in pkgutil.walk_packages([str(probes_root)], prefix="personascope.probes."):
        if info.ispkg:
            continue
        try:
            mod = importlib.import_module(info.name)
            yield info.name, mod, None
        except Exception as e:  # noqa: BLE001 — we want to log any import failure
            yield info.name, None, e


def _factories(mod) -> list[str]:
    return sorted(n for n in getattr(mod, "__all__", []) if n.startswith("make_"))


def build_inventory() -> str:
    by_category: dict[str, list[dict]] = {}
    total_modules = 0
    total_factories = 0
    total_failing = 0

    for qualname, mod, err in _walk_probe_modules():
        total_modules += 1
        # qualname = "personascope.probes.<category>[.external].<module>"
        parts = qualname.split(".")
        category = parts[2] if len(parts) >= 3 else "(uncategorized)"
        is_external = "external" in parts
        short = parts[-1]

        if err is not None:
            total_failing += 1
            row = {
                "file": short, "external": is_external,
                "factories": [], "ok": False, "error": str(err),
            }
        else:
            factories = _factories(mod)
            total_factories += len(factories)
            row = {
                "file": short, "external": is_external,
                "factories": factories, "ok": True, "error": None,
            }

        by_category.setdefault(category, []).append(row)

    # Render markdown
    out: list[str] = []
    out.append("# Probe inventory\n")
    out.append("Auto-generated by `scripts/probe_inventory_audit.py`. "
               "Re-run after adding or moving probes.\n")
    out.append(f"- **Total probe modules:** {total_modules}")
    out.append(f"- **Total `make_*` factories:** {total_factories}")
    out.append(f"- **Import-failing modules:** {total_failing}")
    out.append("")

    for category in sorted(by_category):
        rows = by_category[category]
        out.append(f"## `{category}/`\n")
        out.append("| File | Source | Factories | Import |")
        out.append("|---|---|---|---|")
        for row in sorted(rows, key=lambda r: (r["external"], r["file"])):
            source = "external" if row["external"] else "ours"
            if row["ok"]:
                factories = ", ".join(row["factories"]) if row["factories"] else "—"
                status = "✓"
            else:
                factories = "—"
                status = f"✗ ({row['error']})"
            out.append(f"| `{row['file']}` | {source} | {factories} | {status} |")
        out.append("")

    return "\n".join(out)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out", type=Path, default=None,
        help="If set, write the inventory to this path; otherwise print to stdout.",
    )
    args = parser.parse_args(argv)

    inventory = build_inventory()
    if args.out:
        args.out.write_text(inventory)
        print(f"Wrote {args.out}")
    else:
        print(inventory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
