#!/usr/bin/env python3
"""Emit the run-coverage grid: model x persona x route, per instrument.

What exists on disk, not what it says. A cell is `done` only when it holds
`n_items x n_samples` records; anything short is `part`. Written to stdout as
markdown so TODO.md can hold the current state without anyone hand-editing it.

    python scripts/render_coverage.py > /dev/null          # check it runs
    python scripts/render_coverage.py --out ../personascope-submission/TODO.md
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"

# The grid the paper claims, from configs/models.yaml.
MODELS = [
    ("gpt-4.1", "full ladder"),
    ("qwen38-27b", "full ladder"),
    ("kimi-k2.6", "full ladder"),
    ("claude-sonnet-5", "arm"),
    ("deepseek-v4.1-flash", "arm"),
    ("glm-5.3-flash", "arm"),
    ("gpt-5.6-luna", "arm"),
]
PERSONAS = ["curie", "stalin", "vader", "voldemort"]
ROUTES = ["system", "system_facts_k32", "icl_k32", "sft"]
# `sft` needs a checkpoint; only the full ladder can carry the weight route.
SFT_CAPABLE = {"gpt-4.1", "qwen38-27b", "kimi-k2.6"}


def scan() -> dict:
    """(instrument, model, persona, route) -> (records, expected)."""
    out: dict[tuple[str, str, str, str, str], int] = {}
    mtimes: dict[tuple[str, str], float] = {}
    for f in RESULTS.rglob("responses.jsonl"):
        rel = f.relative_to(RESULTS).parts
        if rel[0] == "legacy":
            continue
        n = sum(1 for _ in f.open())
        if not n:
            continue
        with f.open() as fh:
            r = json.loads(fh.readline())
        model = (r.get("model") or "").replace("-openrouter", "")
        # Older runs named the OpenRouter slug; models.yaml keys on the bare
        # name. See results/legacy/README.md for why that distinction matters.
        model = model.split("/")[-1] if model.startswith("openai/") else model
        key = (r.get("instrument") or rel[0], rel[1], model,
               r.get("persona") or "_base", r.get("route") or "none")
        mtimes[(key[0], key[1])] = max(mtimes.get((key[0], key[1]), 0.0),
                                       f.stat().st_mtime)
        out[key] = n
    # A cell is complete when it holds as many records as the fullest cell of
    # the same RUN -- not the same instrument, since self_report_v2 and v3 ask
    # different question sets. Self-calibrating, and unlike generation.json it
    # is present while a cell is still being written.
    # One run per instrument: the most recently written. Superseded runs stay
    # on disk and in git; a coverage grid is about what still needs asking.
    current: dict[str, str] = {}
    for (inst, run), t in sorted(mtimes.items(), key=lambda kv: kv[1]):
        current[inst] = run
    out = {k: n for k, n in out.items() if current.get(k[0]) == k[1]}
    full: dict[str, int] = defaultdict(int)
    for (inst, *_), n in out.items():
        full[inst] = max(full[inst], n)
    return ({(k[0], k[2], k[3], k[4]): (n, full[k[0]]) for k, n in out.items()},
            current)


INITIAL = {"curie": "C", "stalin": "S", "vader": "D", "voldemort": "V"}


def marks(found, inst, model, route) -> str:
    """Which personas are covered, as initials. Lower-case = partial."""
    out = []
    for p in PERSONAS:
        cell = found.get((inst, model, p, route))
        if cell is None:
            continue
        n, exp = cell
        out.append(INITIAL[p] if n >= exp else INITIAL[p].lower())
    return " ".join(out) if out else "."


def render(scanned) -> str:
    found, current = scanned
    instruments = sorted({k[0] for k in found})
    lines = ["## Run coverage — model x persona x route",
             "",
             "The current run per instrument; superseded runs are on disk",
             "but not here. A cell lists the personas covered; `.` is nothing",
             "run, `--` is not applicable.",
             "Generated by `scripts/render_coverage.py`; do not hand-edit.",
             ""]
    for inst in instruments:
        lines += [f"### {inst}  —  `{current[inst]}`", ""]
        head = ("| model | tier | `_base` | "
                + " | ".join(f"`{r}`" for r in ROUTES) + " |")
        lines += [head, "|---|---|:--:|" + ":--:|" * len(ROUTES)]
        for model, tier in MODELS:
            b = found.get((inst, model, "_base", "none"))
            bm = "." if b is None else ("x" if b[0] >= b[1] else "~")
            cells = []
            for route in ROUTES:
                cells.append("--" if route == "sft" and model not in SFT_CAPABLE
                             else marks(found, inst, model, route))
            lines.append(f"| {model} | {tier} | {bm} | " + " | ".join(cells) + " |")
        lines.append("")
    lines += ["C curie, S stalin, D vader, V voldemort; lower-case = partial.", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None, help="TODO.md to splice into")
    a = ap.parse_args()
    body = render(scan())
    if not a.out:
        print(body)
        return 0
    p = Path(a.out)
    s = p.read_text(encoding="utf-8")
    start = "<!-- COVERAGE:BEGIN -->"
    end = "<!-- COVERAGE:END -->"
    block = f"{start}\n{body}\n{end}"
    if start in s and end in s:
        pre, rest = s.split(start, 1)
        _, post = rest.split(end, 1)
        s = pre + block + post
    else:
        s = s.rstrip() + "\n\n" + block + "\n"
    p.write_text(s, encoding="utf-8")
    print(f"coverage -> {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
